import Head from "next/head";
import Image from "next/image";
import { Poppins } from "next/font/google";
import styles from "@/styles/Home.module.css";
import iconSVG from "../public/icon-arrow.svg";
import useHome from "./hooks";

const poppins400 = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});
const poppins400italic = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  style: ["italic"],
});
const poppins700 = Poppins({
  subsets: ["latin"],
  weight: ["700"],
});
const poppins800 = Poppins({
  subsets: ["latin"],
  weight: ["800"],
});

export default function Home() {
  const {
    handleSubmit,
    setBirthdayDay,
    setBirthdayMonth,
    setBirthdayYear,
    errorBirthdayDay,
    errorBirthdayMonth,
    errorBirthdayYear,
    age,
    months,
    days,
  } = useHome();
  return (
    <>
      <Head>
        <title>Age calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className={styles.main}>
        <h1>Age calculator</h1>
        <section className={styles.card}>
          <form className={styles.form} onSubmit={handleSubmit}>
            <div className={styles.formContent}>
              <div className={styles.formItem}>
                <label
                  htmlFor="day"
                  className={
                    (errorBirthdayDay ? styles.errorLabel : "") +
                    " " +
                    poppins700.className
                  }
                >
                  Day
                </label>
                <input
                  onChange={(e) => setBirthdayDay(+e.target.value)}
                  id="day"
                  name="day"
                  className={
                    (errorBirthdayDay ? styles.error : "") +
                    " " +
                    poppins700.className
                  }
                  type="number"
                  placeholder="DD"
                />
                {errorBirthdayDay && (
                  <p className={poppins400italic.className}>
                    {errorBirthdayDay}
                  </p>
                )}
              </div>
              <div className={styles.formItem}>
                <label
                  htmlFor="month"
                  className={
                    (errorBirthdayDay ? styles.errorLabel : "") +
                    " " +
                    poppins700.className
                  }
                >
                  Month
                </label>
                <input
                  onChange={(e) => setBirthdayMonth(+e.target.value)}
                  id="month"
                  name="month"
                  className={
                    (errorBirthdayDay ? styles.error : "") +
                    " " +
                    poppins700.className
                  }
                  type="number"
                  placeholder="MM"
                />
                {errorBirthdayMonth && (
                  <p className={poppins400italic.className}>
                    {errorBirthdayMonth}
                  </p>
                )}
              </div>
              <div className={styles.formItem}>
                <label
                  htmlFor="year"
                  className={
                    (errorBirthdayDay ? styles.errorLabel : "") +
                    " " +
                    poppins700.className
                  }
                >
                  Year
                </label>
                <input
                  onChange={(e) => setBirthdayYear(+e.target.value)}
                  id="year"
                  name="year"
                  className={
                    (errorBirthdayDay ? styles.error : "") +
                    " " +
                    poppins700.className
                  }
                  type="number"
                  placeholder="YYYY"
                />
                {errorBirthdayYear && (
                  <p className={poppins400italic.className}>
                    {errorBirthdayYear}
                  </p>
                )}
              </div>
            </div>
            <div className={styles.button}>
              <hr color="#dcdcdc" />
              <button type="submit">
                <Image src={iconSVG} alt="Arrow" />
              </button>
              <hr className={styles.hidden} color="#dcdcdc" />
            </div>
          </form>
          <div className={styles.text}>
            <h2 className={poppins800.className}>{age == 0 ? "--" : age}</h2>
            <h3 className={poppins800.className}>years</h3>
          </div>
          <div className={styles.text}>
            <h2 className={poppins800.className}>
              {months == 0 ? "--" : months}
            </h2>
            <h3 className={poppins800.className}>months</h3>
          </div>
          <div className={styles.text}>
            <h2 className={poppins800.className}>{days == 0 ? "--" : days}</h2>
            <h3 className={poppins800.className}>days</h3>
          </div>
        </section>
        <div className={styles.attribution}>
          <p className={poppins400.className}>Challenge by &nbsp;</p>
          <a
            className={poppins400.className}
            href="https://www.frontendmentor.io/challenges/results-summary-component-CE_K6s0maV"
            target="_blank"
          >
            Frontend Mentor
          </a>
          <p className={poppins400.className}>. Coded by &nbsp;</p>
          <a
            className={poppins400.className}
            href="https://github.com/michellepennat"
          >
            Michelle Penna.
          </a>
        </div>
      </main>
    </>
  );
}
